twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    number_format:
        thousands_separator: '.'
    form_themes:
        - 'bootstrap_4_layout.html.twig'
