vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    mappings:
        cliente_upload:
            uri_prefix:         /uploads
            upload_destination: '%kernel.root_dir%/../web/uploads'

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
        avatar_upload:
            uri_prefix:         /image/users
            upload_destination: '%kernel.root_dir%/../web/assets/images/users'

            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true