<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Cliente;
use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{

    public function findEmpresaLike($texto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT c
                                FROM AppBundle:Cliente c
                                WHERE LOWER (c.nome)  LIKE :texto
                                ');
        $consulta->setParameter('texto', '%'.$texto.'%');
        return $consulta->getResult();
    }

    public function findEmpresaLikeTelf($texto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT c
                                FROM AppBundle:Cliente c
                                WHERE c.telefone  LIKE :texto
                                ');
        $consulta->setParameter('texto', '%'.$texto.'%');
        return $consulta->getResult();
    }

    public function findEmpresaLikeContato($texto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT c
                                FROM AppBundle:Cliente c
                                WHERE c.contato  LIKE :texto
                                ');
        $consulta->setParameter('texto', '%'.$texto.'%');
        return $consulta->getResult();
    }

    public function findEmpresaLikeRaoiox($texto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT DISTINCT c
                                FROM AppBundle:Cliente c
                                WHERE c.raiox  LIKE :texto
                                ');
        $consulta->setParameter('texto', '%'.$texto.'%');
        return $consulta->getResult();
    }

    public function findEmpresaLikeEmail($texto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT c
                                FROM AppBundle:Cliente c
                                WHERE c.email LIKE :texto
                                ');
        $consulta->setParameter('texto', '%'.$texto.'%');
        return $consulta->getResult();
    }

    public function findIdLike($texto)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT c.id
                                FROM AppBundle:Cliente c
                                WHERE c.nome LIKE :texto
                                ');
        $consulta->setParameter('texto', '%'.$texto.'%');
        return $consulta->getResult();
    }

    public function findLike($id)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT c
            FROM AppBundle:Cliente c
            WHERE c.nome LIKE :texto
        ');
        $consulta->setParameter('texto', '%'.$id.'%');
        return $consulta->getOneOrNullResult();
    }

    public function findOneWithAddress(Cliente $cliente)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT c, d
                                FROM AppBundle:Cliente c
                                JOIN c.direccion d
                                WHERE c.id = :id
                                ');
        $consulta->setParameter('id', $cliente->getId());
        return $consulta->getOneOrNullResult();
    }

    public function findChamadosXCliente(Cliente $cliente)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT COUNT(c) as cantidad
            FROM AppBundle:Chamado c
            WHERE c.cliente = :cliente
        ');
        $consulta->setParameter('cliente', $cliente->getId());
        return $consulta->getOneOrNullResult();
    }

    public function findUsuariosXCliente(Cliente $cliente)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
            SELECT COUNT(u) as cantidad
            FROM AppBundle:User u
            WHERE u.empresa = :cliente
        ');
        $consulta->setParameter('cliente', $cliente->getId());
        return $consulta->getOneOrNullResult();
    }
}
