<?php

namespace AppBundle\Repository;

/**
 * DefeitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DefeitoRepository extends \Doctrine\ORM\EntityRepository
{
}
