<?php

namespace AppBundle\Repository;

/**
 * EnderecoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnderecoRepository extends \Doctrine\ORM\EntityRepository
{
}
