<?php

namespace AppBundle\Repository;

/**
 * EspecialidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecialidadeRepository extends \Doctrine\ORM\EntityRepository
{
}
