<?php

namespace AppBundle\Repository;

/**
 * EstacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
