<?php

namespace AppBundle\Repository;

/**
 * RoteadorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoteadorRepository extends \Doctrine\ORM\EntityRepository
{
}
