<?php

namespace AppBundle\Repository;

/**
 * TipoEstacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoEstacaoRepository extends \Doctrine\ORM\EntityRepository
{
}
