<?php

namespace AppBundle\Repository;

/**
 * UploadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UploadRepository extends \Doctrine\ORM\EntityRepository
{

    public function findAllByCliente($cliente)
    {
        $em = $this->getEntityManager();
        $consulta = $em->createQuery('
                                SELECT u
                                FROM AppBundle:Upload u
                                WHERE u.cliente = :cliente
                                ');
        $consulta->setParameter('cliente', $cliente);
        return $consulta->getResult();
    }
}
