imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: params.data.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: pt_BR

framework:
    trusted_hosts: ~
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

