# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
#    Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_TECNICO:     ROLE_USER
        ROLE_ADMIN:       ROLE_TECNICO
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                login_path: /login
                check_path: /login_check
                always_use_default_target_path: false
                default_target_path:            /admin
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
            logout_on_user_change: true
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/chamado-tecnico, role: ROLE_USER }
        - { path: ^/admin, role: ROLE_TECNICO }
        - { path: ^/backend/, role: ROLE_TECNICO }
        - { path: ^/admin/tecnicos/, role: ROLE_ADMIN}