# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/cmicro
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-apache-stretch-node-browsers
          environment:
              APP_ENV: test
              DATABASE_URL: mysql://root:root@127.0.0.1/cmicro
              MAILER_FROM: cmicro@expresate.com.br
              MAILER_URL: null://localhost
      - image: circleci/mysql:5.7
          environment:
              MYSQL_ROOT_PASSWORD: 'root'
              MYSQL_DATABASE: cmicro

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mysql:9.4



    steps:
      - checkout
      - run:
          name: Install PHP MySQL
          command: sudo docker-php-ext-install pdo_mysql
      - run:
          name: Wait for MySQL
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Composer
          command: sudo composer self-update
      - run:
          name: Composer install
          command: composer install -n --prefer-dist
      - run:
          name: Run migrations
          command: php bin/console doctrine:migrations:migrate --env=test --no-interaction
#      # Download and cache dependencies
#      - restore_cache:
#          keys:
#          - v1-dependencies-{{ checksum "composer.json" }}
#          # fallback to using the latest cache if no exact match is found
#          - v1-dependencies-
#
#
#      - save_cache:
#          paths:
#            - ./vendor
#          key: v1-dependencies-{{ checksum "composer.json" }}
#
#      # run tests!
#      - run: phpunit