<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TecnicoRepository extends EntityRepository
{
}
