app:
    resource: "../src/AppBundle/Controller/"
    type: annotation
home:
    path: /
    controller: AppBundle\Controller\DefaultController::indexAction
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
